language: php

sudo: false

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7"
  - "hhvm"

matrix:
  allow_failures:
    - php: "7"
    - php: "hhvm"

install: composer install

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover=build/logs/clover.xml

after_script:
  - vendor/bin/coveralls
